const {chromium}=require('playwright');const assert=require('node:assert/strict');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'../app/src/main/assets/game');const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url);if(!file.startsWith(root)||!fs.existsSync(file)){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(resolve=>server.listen(8766,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,...(process.env.TRAFFIC_BROWSER?{executablePath:process.env.TRAFFIC_BROWSER}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766');await page.screenshot({path:path.resolve(__dirname,'../docs/inicio.png')});await page.click('#play');await page.click('#close');assert.equal(await page.locator('#nav').isVisible(),false);assert.equal(await page.locator('#remaining').textContent(),'4 vehículos · 0 choques');
await page.evaluate(()=>{const v=game.cars.find(v=>E.canExit(game.level,v,game.cars));window.firstCar=v.id;});
// Real pointer gesture through the canvas coordinate mapping.
const pos=await page.evaluate(()=>{const v=game.cars.find(v=>v.id===window.firstCar),r=$('#board').getBoundingClientRect(),u=.79/game.level.size;return {x:r.x+r.width*(.105+(v.x+.5)*u),y:r.y+r.height*(.105+(v.y+.5)*u)};});await page.mouse.click(pos.x,pos.y);await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>game.removed.length),1);
await page.click('#undo');assert.equal(await page.evaluate(()=>game.removed.length),0);
await page.click('#hint');assert.equal(await page.evaluate(()=>state.hints),2);assert.ok(await page.evaluate(()=>game.hint!==null));
await page.evaluate(()=>attempt(game.cars.find(v=>E.canExit(game.level,v,game.cars))));await page.waitForTimeout(450);await page.reload();await page.click('#play');assert.equal(await page.evaluate(()=>game.removed.length),1);
await page.screenshot({path:path.resolve(__dirname,'../docs/jugando.png')});
while(await page.evaluate(()=>!game.done)){await page.evaluate(()=>attempt(game.cars.find(v=>E.canExit(game.level,v,game.cars))));await page.waitForTimeout(400);}await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>state.unlocked),2);assert.equal(await page.evaluate(()=>state.coins),135);await page.screenshot({path:path.resolve(__dirname,'../docs/victoria.png')});await page.click('#next');assert.equal(await page.evaluate(()=>game.level.number),2);
await page.evaluate(()=>window.onNativeBack());await page.click('#exit');await page.click('#daily');await page.click('#claim');assert.equal(await page.evaluate(()=>state.coins),165);assert.equal(await page.locator('#claim').isDisabled(),true);await page.click('#close');await page.click('[data-page="garage"]');await page.click('[data-skin="ocean"]');assert.equal(await page.evaluate(()=>state.skin),'classic');
await page.evaluate(()=>{state.coins=200;save();garage();});await page.click('[data-skin="ocean"]');await page.click('#buy');assert.equal(await page.evaluate(()=>state.skin),'ocean');assert.equal(await page.evaluate(()=>state.coins),20);
await page.evaluate(()=>{state.unlocked=500;save();start(500);});await page.waitForTimeout(3000);await page.screenshot({path:path.resolve(__dirname,'../docs/nivel-500.png')});
// Small phone, no horizontal overflow and controls inside screen.
await page.setViewportSize({width:320,height:568});await page.waitForTimeout(100);const dims=await page.evaluate(()=>({w:document.documentElement.scrollWidth,viewport:innerWidth,b:$('#undo').getBoundingClientRect().bottom,h:innerHeight}));assert.ok(dims.w<=dims.viewport);assert.ok(dims.b<=dims.h);assert.deepEqual(errors,[]);
console.log('PASS: gestures, undo, hints, resume, victory, progression, daily reward, garage, level 500, 320px layout; zero JS errors.');await browser.close();server.close();})();
